# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'XCUITest_study' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for XCUITest_study
  pod 'Reusable'

  target 'XCUITest_studyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'XCUITest_studyUITests' do
    # Pods for testing
    pod 'SnapshotTesting', '~> 1.9.0'
    pod 'Reusable'
    pod 'AXSnapshot'
  end

end
